### PR TITLE
Fix `continueOnParseError` incorrectly handling unquoted attribute values that contain `=`

### LINKED ISSUE #257: unexpected-character-in-unquoted-attribute-value error gets parsed incorrectly
[The HTML Standard has this to say when parsing an unquoted attribute value:](https://html.spec.whatwg.org/multipage/parsing.html#attribute-value-(unquoted)-state)

> <dl>
> <dt>U+0022 QUOTATION MARK (")
> <dt>U+0027 APOSTROPHE (')
> <dt>U+003C LESS-THAN SIGN (<)
> <dt>U+003D EQUALS SIGN (=)
> <dt>U+0060 GRAVE ACCENT (`)
>     <dd>This is an unexpected-character-in-unquoted-attribute-value parse error. Treat it as per the "anything else" entry below.
> <dt>…
> <dt>Anything else
>     <dd>Append the current input character to the current attribute's value.
> </dl>

In total: if you encounter these characters, you can either abort, or allow them as part of the attribute value.

Without `continueOnParseError`, html-minifier-next does fine:

```console
$ node_modules/.bin/html-minifier-next <<<'<a href=?b=c>d</a>e'
Minification error:
Parse error at line 1, column 1:
<a href=?b=c>d</a>e
```

But with it, things start to get weird: you lose the `</a>`:

```console
$ node_modules/.bin/html-minifier-next --continue-on-parse-error <<<'<a href=?b=c>d</a>e'
<a href=?b=c>de
```

And for reasons utterly unclear to me (I haven’t dug), adding `decodeEntities` to the mix also changes the first `<` to `&lt;`:

```console
$ node_modules/.bin/html-minifier-next --continue-on-parse-error --decode-entities <<<'<a href=?b=c>d</a>e'
&lt;a href=?b=c>de
```

(I realised this because I was using the `comprehensive` preset, which sets both, and was surprised when `continueOnParseError` by itself yielded different output!)

The expected output (when `continueOnParseError` is set) is:

```html
<a href="?b=c">d</a>e
```

### PR DESCRIPTION
**Pull request by j9t**
Resolves #257

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed an issue where `continueOnParseError` mode incorrectly dropped closing tags when unquoted attribute values contained `=` characters. The parser now correctly preserves tag structure and includes the `=` in the attribute value per error-recovery specifications.

* **Tests**
  * Added comprehensive regression tests for parse error recovery, verifying correct handling of special characters in unquoted attribute values and interaction with related options.

### CODE REVIEW

File: src/htmlparser.js [hunk 1]
```diff
@@ -32,9 +32,12 @@ const singleAttrValues = [
   /"([^"]*)"+/.source,
   // Attr value, single quotes
   /'([^']*)'+/.source,
-  // Attr value, no quotes
+  // Attr value, no quotes (strict: excludes `=` per HTML spec)
   /([^ \t\n\f\r"'`=<>]+)/.source
 ];
+// Lenient unquoted value pattern for `continueOnParseError`: allows `=` per error-recovery rules
+// (unexpected-character-in-unquoted-attribute-value is a parse error but the char is included in the value)
+const singleAttrValueLenientUnquoted = /([^ \t\n\f\r"'`<>]+)/.source;
```
[the remark this answers is not in the document]
Comment (j9t) [reply src/htmlparser.js]: Tweaked and commented, please check.

File: src/htmlparser.js [hunk 2]
```diff
@@ -32,9 +32,14 @@ const singleAttrValues = [
...
   /'([^']*)'+/.source,
-  // Attr value, no quotes
+  // Attr value, no quotes (strict: excludes `=` per HTML spec)
   /([^ \t\n\f\r"'`=<>]+)/.source
 ];
+// Lenient unquoted value pattern for `continueOnParseError`:
+// allows `=` and `` ` `` per spec error-recovery rules
+// (both are parse errors in unquoted-attribute-value state but appended to the value)
+// `"` and `'` remain excluded—permitting them requires broader test coverage
+const singleAttrValueLenientUnquoted = /([^ \t\n\f\r"'<>]+)/.source;
```
Comment (chris-morgan) [inline src/htmlparser.js:42]: You’ve permitted `=` and `` ` `` (great), and remarked on `"` and `'` (understandable, and I think far less common than `=`); but there’s still `<` which should get the same treatment.

Comment (j9t) [reply src/htmlparser.js:42]: Will review, thanks for reviewing and catching this!

(Might be a bit slower over the next few days but have taken note.)

Comment (j9t) [reply src/htmlparser.js:42]: This is correct, overlooked this last night. Patch coming up with https://github.com/j9t/html-minifier-next/pull/263. Thanks, @chris-morgan!
